package net.kalbskinder.helpers.sprites.types;

public enum GuiSprite {
    // Advancement
    ADVANCEMENT_BOX_OBTAINED("advancements/box_obtained"),
    ADVANCEMENT_BOX_UNOBTAINED("advancements/box_unobtained"),
    ADVANCEMENT_CHALLENGE_FRAME_OBTAINED("advancements/challenge_frame_obtained"),
    ADVANCEMENT_CHALLENGE_FRAME_UNOBTAINED("advancements/challenge_frame_unobtained"),
    ADVANCEMENT_GOAL_FRAME_OBTAINED("advancements/goal_frame_obtained"),
    ADVANCEMENT_GOAL_FRAME_UNOBTAINED("advancements/goal_frame_unobtained"),
    ADVANCEMENT_TAB_ABOVE_LEFT("advancements/tab_above_left"),
    ADVANCEMENT_TAB_ABOVE_LEFT_SELECTED("advancements/tab_above_left_selected"),
    ADVANCEMENT_TAB_ABOVE_MIDDLE("advancements/tab_above_middle"),
    ADVANCEMENT_TAB_ABOVE_MIDDLE_SELECTED("advancements/tab_above_middle_selected"),
    ADVANCEMENT_TAB_ABOVE_RIGHT("advancements/tab_above_right"),
    ADVANCEMENT_TAB_ABOVE_RIGHT_SELECTED("advancements/tab_above_right_selected"),
    ADVANCEMENT_TAB_BELOW_LEFT("advancements/tab_below_left"),
    ADVANCEMENT_TAB_BELOW_LEFT_SELECTED("advancements/tab_below_left_selected"),
    ADVANCEMENT_TAB_BELOW_MIDDLE("advancements/tab_below_middle"),
    ADVANCEMENT_TAB_BELOW_MIDDLE_SELECTED("advancements/tab_below_middle_selected"),
    ADVANCEMENT_TAB_BELOW_RIGHT("advancements/tab_below_right"),
    ADVANCEMENT_TAB_BELOW_RIGHT_SELECTED("advancements/tab_below_right_selected"),
    ADVANCEMENT_TAB_LEFT_BOTTOM("advancements/tab_left_bottom"),
    ADVANCEMENT_TAB_LEFT_BOTTOM_SELECTED("advancements/tab_left_bottom_selected"),
    ADVANCEMENT_TAB_LEFT_MIDDLE("advancements/tab_left_middle"),
    ADVANCEMENT_TAB_LEFT_MIDDLE_SELECTED("advancements/tab_left_middle_selected"),
    ADVANCEMENT_TAB_LEFT_TOP("advancements/tab_left_top"),
    ADVANCEMENT_TAB_LEFT_TOP_SELECTED("advancements/tab_left_top_selected"),
    ADVANCEMENT_TAB_RIGHT_BOTTOM("advancements/tab_right_bottom"),
    ADVANCEMENT_TAB_RIGHT_BOTTOM_SELECTED("advancements/tab_right_bottom_selected"),
    ADVANCEMENT_TAB_RIGHT_MIDDLE("advancements/tab_right_middle"),
    ADVANCEMENT_TAB_RIGHT_MIDDLE_SELECTED("advancements/tab_right_middle_selected"),
    ADVANCEMENT_TAB_RIGHT_TOP("advancements/tab_right_top"),
    ADVANCEMENT_TAB_RIGHT_TOP_SELECTED("advancements/tab_right_top_selected"),
    ADVANCEMENT_TASK_FRAME_OBTAINED("advancements/task_frame_obtained"),
    ADVANCEMENT_TASK_FRAME_UNOBTAINED("advancements/task_frame_unobtained"),
    ADVANCEMENT_TITLE_BOX("advancements/title_box"),

    // BossBar
    BOSS_BAR_BLUE_BACKGROUND("boss_bar/blue_background"),
    BOSS_BAR_BLUE_PROGRESS("boss_bar/blue_progress"),
    BOSS_BAR_GREEN_BACKGROUND("boss_bar/green_background"),
    BOSS_BAR_GREEN_PROGRESS("boss_bar/green_progress"),
    BOSS_BAR_NOTCHED_10_BACKGROUND("boss_bar/notched_10_background"),
    BOSS_BAR_NOTCHED_10_PROGRESS("boss_bar/notched_10_progress"),
    BOSS_BAR_NOTCHED_12_BACKGROUND("boss_bar/notched_12_background"),
    BOSS_BAR_NOTCHED_12_PROGRESS("boss_bar/notched_12_progress"),
    BOSS_BAR_NOTCHED_20_BACKGROUND("boss_bar/notched_20_background"),
    BOSS_BAR_NOTCHED_20_PROGRESS("boss_bar/notched_20_progress"),
    BOSS_BAR_NOTCHED_6_BACKGROUND("boss_bar/notched_6_background"),
    BOSS_BAR_NOTCHED_6_PROGRESS("boss_bar/notched_6_progress"),
    BOSS_BAR_PINK_BACKGROUND("boss_bar/pink_background"),
    BOSS_BAR_PINK_PROGRESS("boss_bar/pink_progress"),
    BOSS_BAR_PURPLE_BACKGROUND("boss_bar/purple_background"),
    BOSS_BAR_PURPLE_PROGRESS("boss_bar/purple_progress"),
    BOSS_BAR_RED_BACKGROUND("boss_bar/red_background"),
    BOSS_BAR_RED_PROGRESS("boss_bar/red_progress"),
    BOSS_BAR_WHITE_BACKGROUND("boss_bar/white_background"),
    BOSS_BAR_WHITE_PROGRESS("boss_bar/white_progress"),
    BOSS_BAR_YELLOW_BACKGROUND("boss_bar/yellow_background"),
    BOSS_BAR_YELLOW_PROGRESS("boss_bar/yellow_progress"),

    // Container
    CONTAINER_ANVIL_ERROR("container/anvil/error"),
    CONTAINER_ANVIL_TEXT_FIELD("container/anvil/text_field"),
    CONTAINER_ANVIL_TEXT_FIELD_DISABLED("container/anvil/text_field_disabled"),
    CONTAINER_BEACON_BUTTON("container/beacon/button"),
    CONTAINER_BEACON_BUTTON_DISABLED("container/beacon/button_disabled"),
    CONTAINER_BEACON_BUTTON_HIGHLIGHTED("container/beacon/button_highlighted"),
    CONTAINER_BEACON_BUTTON_SELECTED("container/beacon/button_selected"),
    CONTAINER_BEACON_CANCEL("container/beacon/cancel"),
    CONTAINER_BEACON_CONFIRM("container/beacon/confirm"),
    CONTAINER_BLAST_FURNACE_BURN_PROGRESS("container/blast_furnace/burn_progress"),
    CONTAINER_BLAST_FURNACE_LIT_PROGRESS("container/blast_furnace/lit_progress"),
    CONTAINER_BREWING_STAND_BREW_PROGRESS("container/brewing_stand/brew_progress"),
    CONTAINER_BREWING_STAND_BUBBLES("container/brewing_stand/bubbles"),
    CONTAINER_BREWING_STAND_FUEL_LENGTH("container/brewing_stand/fuel_length"),
    CONTAINER_BUNDLE_BUNDLE_PROGRESSBAR_BORDER("container/bundle/bundle_progressbar_border"),
    CONTAINER_BUNDLE_BUNDLE_PROGRESSBAR_FILL("container/bundle/bundle_progressbar_fill"),
    CONTAINER_BUNDLE_BUNDLE_PROGRESSBAR_FULL("container/bundle/bundle_progressbar_full"),
    CONTAINER_BUNDLE_SLOT_BACKGROUND("container/bundle/bundle_slot_background"),
    CONTAINER_BUNDLE_SLOT_HIGHLIGHT_BACK("container/bundle/slot_highlight_back"),
    CONTAINER_BUNDLE_SLOT_HIGHLIGHT_FRONT("container/bundle/slot_highlight_front"),
    CONTAINER_CARTOGRAPHY_TABLE_DUPLICATED_MAP("container/cartography_table/duplicated_map"),
    CONTAINER_CARTOGRAPHY_TABLE_ERROR("container/cartography_table/error"),
    CONTAINER_CARTOGRAPHY_TABLE_LOCKED("container/cartography_table/locked"),
    CONTAINER_CARTOGRAPHY_TABLE_MAP("container/cartography_table/map"),
    CONTAINER_CARTOGRAPHY_TABLE_SCALED_MAP("container/cartography_table/scaled_map"),
    CONTAINER_CRAFTER_DISABLED_SLOT("container/crafter/disabled_slot"),
    CONTAINER_CRAFTER_POWERED_REDSTONE("container/crafter/powered_redstone"),
    CONTAINER_CRAFTER_UNPOWERED_REDSTONE("container/crafter/unpowered_redstone"),
    CONTAINER_CREATIVE_INVENTORY_SCROLLER("container/creative_inventory/scroller"),
    CONTAINER_CREATIVE_INVENTORY_SCROLLER_DISABLED("container/creative_inventory/scroller_disabled"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_1("container/creative_inventory/tab_bottom_selected_1"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_2("container/creative_inventory/tab_bottom_selected_2"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_3("container/creative_inventory/tab_bottom_selected_3"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_4("container/creative_inventory/tab_bottom_selected_4"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_5("container/creative_inventory/tab_bottom_selected_5"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_6("container/creative_inventory/tab_bottom_selected_6"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_SELECTED_7("container/creative_inventory/tab_bottom_selected_7"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_1("container/creative_inventory/tab_bottom_unselected_1"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_2("container/creative_inventory/tab_bottom_unselected_2"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_3("container/creative_inventory/tab_bottom_unselected_3"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_4("container/creative_inventory/tab_bottom_unselected_4"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_5("container/creative_inventory/tab_bottom_unselected_5"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_6("container/creative_inventory/tab_bottom_unselected_6"),
    CONTAINER_CREATIVE_INVENTORY_TAB_BOTTOM_UNSELECTED_7("container/creative_inventory/tab_bottom_unselected_7"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_1("container/creative_inventory/tab_top_selected_1"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_2("container/creative_inventory/tab_top_selected_2"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_3("container/creative_inventory/tab_top_selected_3"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_4("container/creative_inventory/tab_top_selected_4"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_5("container/creative_inventory/tab_top_selected_5"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_6("container/creative_inventory/tab_top_selected_6"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_SELECTED_7("container/creative_inventory/tab_top_selected_7"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_1("container/creative_inventory/tab_top_unselected_1"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_2("container/creative_inventory/tab_top_unselected_2"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_3("container/creative_inventory/tab_top_unselected_3"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_4("container/creative_inventory/tab_top_unselected_4"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_5("container/creative_inventory/tab_top_unselected_5"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_6("container/creative_inventory/tab_top_unselected_6"),
    CONTAINER_CREATIVE_INVENTORY_TAB_TOP_UNSELECTED_7("container/creative_inventory/tab_top_unselected_7"),
    CONTAINER_ENCHANTING_TABLE_ENCHANTMENT_SLOT("container/enchanting_table_/enchantment_slot"),
    CONTAINER_ENCHANTING_TABLE_ENCHANTMENT_SLOT_DISABLED("container/enchanting_table_/enchantment_slot_disabled"),
    CONTAINER_ENCHANTING_TABLE_ENCHANTMENT_SLOT_HIGHLIGHTED("container/enchanting_table_/enchantment_slot_highlighted"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_1("container/enchanting_table_/level_1"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_1_DISABLED("container/enchanting_table_/level_1_disabled"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_2("container/enchanting_table_/level_2"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_2_DISABLED("container/enchanting_table_/level_2_disabled"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_3("container/enchanting_table_/level_3"),
    CONTAINER_ENCHANTING_TABLE_LEVEL_3_DISABLED("container/enchanting_table_/level_3_disabled"),
    CONTAINER_FURNACE_BURN_PROGRESS("container/furnace/burn_progress"),
    CONTAINER_FURNACE_LIT_PROGRESS("container/furnace/lit_progress"),
    CONTAINER_GRINDSTONE_ERROR("container/grindstone/error"),
    CONTAINER_HORSE_CHEST_SLOTS("container/horse/chest_slots"),
    CONTAINER_INVENTORY_EFFECT_BACKGROUND("container/inventory/effect_background"),
    CONTAINER_INVENTORY_EFFECT_BACKGROUND_AMBIENT("container/inventory/effect_background_ambient"),
    CONTAINER_LOOM_ERROR("container/loom/error"),
    CONTAINER_LOOM_PATTERN("container/loom/pattern"),
    CONTAINER_LOOM_PATTERN_HIGHLIGHTED("container/loom/pattern_highlighted"),
    CONTAINER_LOOM_PATTERN_SELECTED("container/loom/pattern_selected"),
    CONTAINER_LOOM_SCROLLER("container/loom/scroller"),
    CONTAINER_LOOM_SCROLLER_DISABLED("container/loom/scroller_disabled"),
    CONTAINER_SLOT("container/slot"),
    CONTAINER_SLOT_AMETHYST_SHARD("container/slot/amethyst_shard"),
    CONTAINER_SLOT_AXE("container/slot/axe"),
    CONTAINER_SLOT_BANNER("container/slot/banner"),
    CONTAINER_SLOT_BANNER_PATTERN("container/slot/banner_pattern"),
    CONTAINER_SLOT_BOOTS("container/slot/boots"),
    CONTAINER_SLOT_BREWING_FUEL("container/slot/brewing_fuel"),
    CONTAINER_SLOT_CHESTPLATE("container/slot/chestplate"),
    CONTAINER_SLOT_DIAMOND("container/slot/diamond"),
    CONTAINER_SLOT_DYE("container/slot/dye"),
    CONTAINER_SLOT_EMERALD("container/slot/emerald"),
    CONTAINER_SLOT_HELMET("container/slot/helmet"),
    CONTAINER_SLOT_HIGHLIGHT_BACK("container/slot_highlight_back"),
    CONTAINER_SLOT_HIGHLIGHT_FRONT("container/slot_highlight_front"),
    CONTAINER_SLOT_HOE("container/slot/hoe"),
    CONTAINER_SLOT_HORSE_ARMOR("container/slot/horse_armor"),
    CONTAINER_SLOT_INGOT("container/slot/ingot"),
    CONTAINER_SLOT_LAPIS_LAZULI("container/slot/lapis_lazuli"),
    CONTAINER_SLOT_LEGGINGS("container/slot/leggings"),
    CONTAINER_SLOT_LLAMA_ARMOR("container/slot/llama_armor"),
    CONTAINER_SLOT_NAUTILUS_ARMOR("container/slot/nautilus_armor"),
    CONTAINER_SLOT_NAUTILUS_ARMOR_INVENTORY("container/slot/nautilus_armor_inventory"),
    CONTAINER_SLOT_PICKAXE("container/slot/pickaxe"),
    CONTAINER_SLOT_POTION("container/slot/potion"),
    CONTAINER_SLOT_QUARTZ("container/slot/quartz"),
    CONTAINER_SLOT_REDSTONE_DUST("container/slot/redstone_dust"),
    CONTAINER_SLOT_SADDLE("container/slot/saddle"),
    CONTAINER_SLOT_SHIELD("container/slot/shield"),
    CONTAINER_SLOT_SHOVEL("container/slot/shovel"),
    CONTAINER_SLOT_SMITHING_TEMPLATE_ARMOR_TRIM("container/slot/smithing_template_armor_trim"),
    CONTAINER_SLOT_SMITHING_TEMPLATE_NETHERITE_UPGRADE("container/slot/smithing_template_netherite_upgrade"),
    CONTAINER_SLOT_SPEAR("container/slot/spear"),
    CONTAINER_SLOT_SWORD("container/slot/sword"),
    CONTAINER_SMITHING_ERROR("container/smithing/error"),
    CONTAINER_SMOKER_BURN_PROGRESS("container/smoker/burn_progress"),
    CONTAINER_SMOKER_LIT_PROGRESS("container/smoker/lit_progress"),
    CONTAINER_STONECUTTER_RECIPE("container/stonecutter/recipe"),
    CONTAINER_STONECUTTER_RECIPE_HIGHLIGHTED("container/stonecutter/recipe_highlighted"),
    CONTAINER_STONECUTTER_RECIPE_SELECTED("container/stonecutter/recipe_selected"),
    CONTAINER_STONECUTTER_SCROLLER("container/stonecutter/scroller"),
    CONTAINER_STONECUTTER_SCROLLER_DISABLED("container/stonecutter/scroller_disabled"),
    CONTAINER_VILLAGER_DISCOUNT_STRIKETHROUGH("container/villager/discount_strikethrough"),
    CONTAINER_VILLAGER_EXPERIENCE_BAR_BACKGROUND("container/villager/experience_bar_background"),
    CONTAINER_VILLAGER_EXPERIENCE_BAR_CURRENT("container/villager/experience_bar_current"),
    CONTAINER_VILLAGER_EXPERIENCE_BAR_RESULT("container/villager/experience_bar_result"),
    CONTAINER_VILLAGER_OUT_OF_STOCK("container/villager/out_of_stock"),
    CONTAINER_VILLAGER_SCROLLER("container/villager/scroller"),
    CONTAINER_VILLAGER_SCROLLER_DISABLED("container/villager/scroller_disabled"),
    CONTAINER_VILLAGER_TRADE_ARROW("container/villager/trade_arrow"),
    CONTAINER_VILLAGER_TRADE_ARROW_OUT_OF_STOCK("container/villager/trade_arrow_out_of_stock"),

    // Dialog
    DIALOG_WARNING_BUTTON("dialog/warning_button"),
    DIALOG_WARNING_BUTTON_DISABLED("dialog/warning_button_disabled"),
    DIALOG_WARNING_BUTTON_HIGHLIGHTED("dialog/warning_button_highlighted"),

    // GameModeSwitcher
    GAME_MODE_SWITCHER_SELECTION("gamemode_switcher/selection"),
    GAME_MODE_SWITCHER_SLOT("gamemode_switcher/slot"),

    // Hud
    HUD_AIR("hud/air"),
    HUD_AIR_BURSTING("hud/air_bursting"),
    HUD_AIR_EMPTY("hud/air_empty"),
    HUD_ARMOR_EMPTY("hud/armor_empty"),
    HUD_ARMOR_FULL("hud/armor_full"),
    HUD_ARMOR_HALF("hud/armor_half"),
    HUD_CROSSHAIR("hud/crosshair"),
    HUD_CROSSHAIR_ATTACK_INDICATOR_BACKGROUND("hud/crosshair_attack_indicator_background"),
    HUD_CROSSHAIR_ATTACK_INDICATOR_FULL("hud/crosshair_attack_indicator_full"),
    HUD_CROSSHAIR_ATTACK_INDICATOR_PROGRESS("hud/crosshair_attack_indicator_progress"),
    HUD_EFFECT_BACKGROUND("hud/effect_background"),
    HUD_EFFECT_BACKGROUND_AMBIENT("hud/effect_background_ambient"),
    HUD_EXPERIENCE_BAR_BACKGROUND("hud/experience_bar_background"),
    HUD_EXPERIENCE_BAR_PROGRESS("hud/experience_bar_progress"),
    HUD_FOOD_EMPTY("hud/food_empty"),
    HUD_FOOD_EMPTY_HUNGER("hud/food_empty_hunger"),
    HUD_FOOD_FULL("hud/food_full"),
    HUD_FOOD_FULL_HUNGER("hud/food_full_hunger"),
    HUD_FOOD_HALF("hud/food_half"),
    HUD_FOOD_HALF_HUNGER("hud/food_half_hunger"),
    HUD_HEART_ABSORBING_FULL("hud/heart/absorbing_full"),
    HUD_HEART_ABSORBING_FULL_BLINKING("hud/heart/absorbing_full_blinking"),
    HUD_HEART_ABSORBING_HALF("hud/heart/absorbing_half"),
    HUD_HEART_ABSORBING_HALF_BLINKING("hud/heart/absorbing_half_blinking"),
    HUD_HEART_ABSORBING_HARDCORE_FULL("hud/heart/absorbing_hardcore_full"),
    HUD_HEART_ABSORBING_HARDCORE_FULL_BLINKING("hud/heart/absorbing_hardcore_full_blinking"),
    HUD_HEART_ABSORBING_HARDCORE_HALF("hud/heart/absorbing_hardcore_half"),
    HUD_HEART_ABSORBING_HARDCORE_HALF_BLINKING("hud/heart/absorbing_hardcore_half_blinking"),
    HUD_HEART_CONTAINER("hud/heart/container"),
    HUD_HEART_CONTAINER_BLINKING("hud/heart/blinking"),
    HUD_HEART_CONTAINER_HARDCORE("hud/heart/hardcore"),
    HUD_HEART_CONTAINER_HARDCORE_BLINKING("hud/heart/hardcore_blinking"),
    HUD_HEART_FROZEN_FULL("hud/heart/frozen_full"),
    HUD_HEART_FROZEN_FULL_BLINKING("hud/heart/frozen_full_blinking"),
    HUD_HEART_FROZEN_HALF("hud/heart/frozen_half"),
    HUD_HEART_FROZEN_HALF_BLINKING("hud/heart/frozen_half_blinking"),
    HUD_HEART_FROZEN_HARDCORE_FULL("hud/heart/frozen_hardcore_full"),
    HUD_HEART_FROZEN_HARDCORE_FULL_BLINKING("hud/heart/frozen_hardcore_full_blinking"),
    HUD_HEART_FROZEN_HARDCORE_HALF("hud/heart/frozen_hardcore_half"),
    HUD_HEART_FROZEN_HARDCORE_HALF_BLINKING("hud/heart/frozen_hardcore_half_blinking"),
    HUD_HEART_FULL("hud/heart/full"),
    HUD_HEART_FULL_BLINKING("hud/heart/full_blinking"),
    HUD_HEART_HALF("hud/heart/half"),
    HUD_HEART_HALF_BLINKING("hud/heart/half_blinking"),
    HUD_HEART_HARDCORE_FULL("hud/heart/hardcore_full"),
    HUD_HEART_HARDCORE_FULL_BLINKING("hud/heart/hardcore_full_blinking"),
    HUD_HEART_HARDCORE_HALF("hud/heart/hardcore_half"),
    HUD_HEART_HARDCORE_HALF_BLINKING("hud/heart/hardcore_half_blinking"),
    HUD_HEART_POISONED_FULL("hud/heart/poisoned_full"),
    HUD_HEART_POISONED_FULL_BLINKING("hud/heart/poisoned_full_blinking"),
    HUD_HEART_POISONED_HALF("hud/heart/poisoned_half"),
    HUD_HEART_POISONED_HALF_BLINKING("hud/heart/poisoned_half_blinking"),
    HUD_HEART_POISONED_HARDCORE_FULL("hud/heart/poisoned_hardcore_full"),
    HUD_HEART_POISONED_HARDCORE_FULL_BLINKING("hud/heart/poisoned_hardcore_full_blinking"),
    HUD_HEART_POISONED_HARDCORE_HALF("hud/heart/poisoned_hardcore_half"),
    HUD_HEART_POISONED_HARDCORE_HALF_BLINKING("hud/heart/poisoned_hardcore_half_blinking"),
    HUD_HEART_VEHICLE_CONTAINER("hud/heart/vehicle_container"),
    HUD_HEART_VEHICLE_FULL("hud/heart/vehicle_full"),
    HUD_HEART_VEHICLE_HALF("hud/heart/vehicle_half"),
    HUD_HEART_WITHERED_FULL("hud/heart/withered_full"),
    HUD_HEART_WITHERED_FULL_BLINKING("hud/heart/withered_full_blinking"),
    HUD_HEART_WITHERED_HALF("hud/heart/withered_half"),
    HUD_HEART_WITHERED_HALF_BLINKING("hud/heart/withered_half_blinking"),
    HUD_HEART_WITHERED_HARDCORE_FULL("hud/heart/withered_hardcore_full"),
    HUD_HEART_WITHERED_HARDCORE_FULL_BLINKING("hud/heart/withered_hardcore_full_blinking"),
    HUD_HEART_WITHERED_HARDCORE_HALF("hud/heart/withered_hardcore_half"),
    HUD_HEART_WITHERED_HARDCORE_HALF_BLINKING("hud/heart/withered_hardcore_half_blinking"),
    HUD_HOTBAR("hud/hotbar"),
    HUD_HOTBAR_ATTACK_INDICATOR_BACKGROUND("hud/hotbar_attack_indicator_background"),
    HUD_HOTBAR_ATTACK_INDICATOR_PROGRESS("hud/hotbar_attack_indicator_progress"),
    HUD_HOTBAR_OFFHAND_LEFT("hud/hotbar_offhand_left"),
    HUD_HOTBAR_OFFHAND_RIGHT("hud/hotbar_offhand_right"),
    HUD_HOTBAR_SELECTION("hud/hotbar_selection"),
    HUD_JUMP_BAR_BACKGROUND("hud/jump_bar_background"),
    HUD_JUMP_BAR_COOLDOWN("hud/jump_bar_cooldown"),
    HUD_JUMP_BAR_PROGRESS("hud/jump_bar_progress"),
    HUD_LOCATOR_BAR_ARROW_DOWN("hud/locator_bar_arrow_down"),
    HUD_LOCATOR_BAR_ARROW_UP("hud/locator_bar_arrow_up"),
    HUD_LOCATOR_BAR_BACKGROUND("hud/locator_bar_background"),
    HUD_LOCATOR_BAR_DOT_BOWTIE("hud/locator_bar_dot_bowtie"),
    HUD_LOCATOR_BAR_DOT_DEFAULT_0("hud/locator_bar_dot_default_0"),
    HUD_LOCATOR_BAR_DOT_DEFAULT_1("hud/locator_bar_dot_default_1"),
    HUD_LOCATOR_BAR_DOT_DEFAULT_2("hud/locator_bar_dot_default_2"),
    HUD_LOCATOR_BAR_DOT_DEFAULT_3("hud/locator_bar_dot_default_3"),

    // Icon
    ICON_ACCESSIBILITY("icon/accessibility"),
    ICON_CHAT_MODIFIED("icon/chat_modified"),
    ICON_CHECKMARK("icon/checkmark"),
    ICON_DRAFT_REPORT("icon/draft_report"),
    ICON_INFO("icon/info"),
    ICON_INVITE("icon/invite"),
    ICON_LANGUAGE("icon/language"),
    ICON_LINK("icon/link"),
    ICON_LINK_HIGHLIGHTED("icon/link_highlighted"),
    ICON_MUSIC_NOTES("icon/music_notes"),
    ICON_NEW_REALM("icon/new_realm"),
    ICON_NEWS("icon/news"),
    ICON_PING_1("icon/ping_1"),
    ICON_PING_2("icon/ping_2"),
    ICON_PING_3("icon/ping_3"),
    ICON_PING_4("icon/ping_4"),
    ICON_PING_5("icon/ping_5"),
    ICON_PING_UNKNOWN("icon/ping_unknown"),
    ICON_SEARCH("icon/search"),
    ICON_TRIAL_AVAILABLE("icon/trial_available"),
    ICON_UNSEEN_NOTIFICATION("icon/unseen_notification"),
    ICON_VIDEO_LINK("icon/video_link"),
    ICON_VIDEO_LINK_HIGHLIGHTED("icon/video_link_highlighted"),

    // Notification
    NOTIFICATION_NOTIFICATION_1("notification/1"),
    NOTIFICATION_NOTIFICATION_2("notification/2"),
    NOTIFICATION_NOTIFICATION_3("notification/3"),
    NOTIFICATION_NOTIFICATION_4("notification/4"),
    NOTIFICATION_NOTIFICATION_5("notification/5"),
    NOTIFICATION_NOTIFICATION_MORE("notification/more"),

    // PendingInvite
    PENDING_INVITE_ACCEPT("pending_invite/accept"),
    PENDING_INVITE_ACCEPT_HIGHLIGHTED("pending_invite/accept_highlighted"),
    PENDING_INVITE_REJECT("pending_invite/reject"),
    PENDING_INVITE_REJECT_HIGHLIGHTED("pending_invite/reject_highlighted"),

    // PlayerList
    PLAYER_LIST_MAKE_OPERATOR("player_list/make_operator"),
    PLAYER_LIST_REMOVE_OPERATOR("player_list/remove_operator"),
    PLAYER_LIST_REMOVE_PLAYER("player_list/remove_player"),

    // Popup
    POPUP_BACKGROUND("popup/background"),

    // RealmStatus
    REALM_STATUS_CLOSED("realm_status/closed"),
    REALM_STATUS_EXPIRED("realm_status/expired"),
    REALM_STATUS_EXPIRES_SOON("realm_status/expires_soon"),
    REALM_STATUS_OPEN("realm_status/open"),

    // RecipeBook
    RECIPE_BOOK_BUTTON("recipe_book/button"),
    RECIPE_BOOK_BUTTON_HIGHLIGHTED("recipe_book/button_highlighted"),
    RECIPE_BOOK_CRAFTING_OVERLAY("recipe_book/crafting_overlay"),
    RECIPE_BOOK_CRAFTING_OVERLAY_DISABLED("recipe_book/crafting_overlay_disabled"),
    RECIPE_BOOK_CRAFTING_OVERLAY_DISABLED_HIGHLIGHTED("recipe_book/crafting_overlay_disabled_highlighted"),
    RECIPE_BOOK_CRAFTING_OVERLAY_HIGHLIGHTED("recipe_book/crafting_overlay_highlighted"),
    RECIPE_BOOK_FILTER_DISABLED("recipe_book/filter_disabled"),
    RECIPE_BOOK_FILTER_DISABLED_HIGHLIGHTED("recipe_book/filter_disabled_highlighted"),
    RECIPE_BOOK_FILTER_ENABLED("recipe_book/filter_enabled"),
    RECIPE_BOOK_FILTER_ENABLED_HIGHLIGHTED("recipe_book/filter_enabled_highlighted"),
    RECIPE_BOOK_FURNACE_FILTER_DISABLED("recipe_book/furnace_filter_disabled"),
    RECIPE_BOOK_FURNACE_FILTER_DISABLED_HIGHLIGHTED("recipe_book/furnace_filter_disabled_highlighted"),
    RECIPE_BOOK_FURNACE_FILTER_ENABLED("recipe_book/furnace_filter_enabled"),
    RECIPE_BOOK_FURNACE_FILTER_ENABLED_HIGHLIGHTED("recipe_book/furnace_filter_enabled_highlighted"),
    RECIPE_BOOK_FURNACE_OVERLAY("recipe_book/furnace_overlay"),
    RECIPE_BOOK_FURNACE_OVERLAY_DISABLED("recipe_book/furnace_overlay_disabled"),
    RECIPE_BOOK_FURNACE_OVERLAY_DISABLED_HIGHLIGHTED("recipe_book/furnace_overlay_disabled_highlighted"),
    RECIPE_BOOK_FURNACE_OVERLAY_HIGHLIGHTED("recipe_book/furnace_overlay_highlighted"),
    RECIPE_BOOK_OVERLAY_RECIPE("recipe_book/overlay_recipe"),
    RECIPE_BOOK_PAGE_BACKWARD("recipe_book/page_backward"),
    RECIPE_BOOK_PAGE_BACKWARD_HIGHLIGHTED("recipe_book/page_backward_highlighted"),
    RECIPE_BOOK_PAGE_FORWARD("recipe_book/page_forward"),
    RECIPE_BOOK_PAGE_FORWARD_HIGHLIGHTED("recipe_book/page_forward_highlighted"),
    RECIPE_BOOK_SLOT_CRAFTABLE("recipe_book/slot_craftable"),
    RECIPE_BOOK_SLOT_MANY_CRAFTABLE("recipe_book/slot_many_craftable"),
    RECIPE_BOOK_SLOT_MANY_UNCRAFTABLE("recipe_book/slot_many_uncraftable"),
    RECIPE_BOOK_SLOT_UNCRAFTABLE("recipe_book/slot_uncraftable"),
    RECIPE_BOOK_TAB("recipe_book/tab"),
    RECIPE_BOOK_TAB_SELECTED("recipe_book/tab_selected"),

    // ServerList
    SERVER_LIST_INCOMPATIBLE("server_list/incompatible"),
    SERVER_LIST_JOIN("server_list/join"),
    SERVER_LIST_JOIN_HIGHLIGHTED("server_list/join_highlighted"),
    SERVER_LIST_MOVE_DOWN("server_list/move_down"),
    SERVER_LIST_MOVE_DOWN_HIGHLIGHTED("server_list/move_down_highlighted"),
    SERVER_LIST_MOVE_UP("server_list/move_up"),
    SERVER_LIST_MOVE_UP_HIGHLIGHTED("server_list/move_up_highlighted"),
    SERVER_LIST_PING_1("server_list/ping_1"),
    SERVER_LIST_PING_2("server_list/ping_2"),
    SERVER_LIST_PING_3("server_list/ping_3"),
    SERVER_LIST_PING_4("server_list/ping_4"),
    SERVER_LIST_PING_5("server_list/ping_5"),
    SERVER_LIST_PINGING_1("server_list/pinging_1"),
    SERVER_LIST_PINGING_2("server_list/pinging_2"),
    SERVER_LIST_PINGING_3("server_list/pinging_3"),
    SERVER_LIST_PINGING_4("server_list/pinging_4"),
    SERVER_LIST_PINGING_5("server_list/pinging_5"),
    SERVER_LIST_UNREACHABLE("server_list/unreachable"),

    // SocialInteractions
    SOCIAL_INTERACTIONS_BACKGROUND("social_interactions/background"),
    SOCIAL_INTERACTIONS_MUTE_BUTTON("social_interactions/mute_button"),
    SOCIAL_INTERACTIONS_MUTE_BUTTON_HIGHLIGHTED("social_interactions/mute_button_highlighted"),
    SOCIAL_INTERACTIONS_REPORT_BUTTON("social_interactions/report_button"),
    SOCIAL_INTERACTIONS_REPORT_BUTTON_DISABLED("social_interactions/report_button_disabled"),
    SOCIAL_INTERACTIONS_REPORT_BUTTON_HIGHLIGHTED("social_interactions/report_button_highlighted"),
    SOCIAL_INTERACTIONS_UNMUTE_BUTTON("social_interactions/unmute_button"),
    SOCIAL_INTERACTIONS_UNMUTE_BUTTON_HIGHLIGHTED("social_interactions/unmute_button_highlighted"),

    // Spectator
    SPECTATOR_CLOSE("spectator/close"),
    SPECTATOR_SCROLL_LEFT("spectator/scroll_left"),
    SPECTATOR_SCROLL_RIGHT("spectator/scroll_right"),
    SPECTATOR_TELEPORT_TO_PLAYER("spectator/teleport_to_player"),
    SPECTATOR_TELEPORT_TO_TEAM("spectator/teleport_to_team"),

    // Statistics
    STATISTICS_BLOCK_MINED("statistics/block_mined"),
    STATISTICS_HEADER("statistics/header"),
    STATISTICS_ITEM_BROKEN("statistics/item_broken"),
    STATISTICS_ITEM_CRAFTED("statistics/item_crafted"),
    STATISTICS_ITEM_DROPPED("statistics/item_dropped"),
    STATISTICS_ITEM_PICKED_UP("statistics/item_picked_up"),
    STATISTICS_ITEM_USED("statistics/item_used"),
    STATISTICS_SORT_DOWN("statistics/sort_down"),
    STATISTICS_SORT_UP("statistics/sort_up"),

    // Toast
    TOAST_ADVANCEMENT("toast/advancement"),
    TOAST_MOUSE("toast/mouse"),
    TOAST_MOVEMENT_KEYS("toast/movement_keys"),
    TOAST_NOW_PLAYING("toast/now_playing"),
    TOAST_RECIPE("toast/recipe"),
    TOAST_RECIPE_BOOK("toast/recipe_book"),
    TOAST_RIGHT_CLICK("toast/right_click"),
    TOAST_SOCIAL_INTERACTIONS("toast/social_interactions"),
    TOAST_SYSTEM("toast/system"),
    TOAST_TREE("toast/tree"),
    TOAST_TUTORIAL("toast/tutorial"),
    TOAST_WOODEN_PLANKS("toast/wooden_planks"),

    // Tooltip
    TOOLTIP_BACKGROUND("tooltip/background"),
    TOOLTIP_FRAME("tooltip/frame"),

    // TransferableList
    TRANSFERABLE_LIST_MOVE_DOWN("transferable_list/move_down"),
    TRANSFERABLE_LIST_MOVE_DOWN_HIGHLIGHTED("transferable_list/move_down_highlighted"),
    TRANSFERABLE_LIST_MOVE_UP("transferable_list/move_up"),
    TRANSFERABLE_LIST_MOVE_UP_HIGHLIGHTED("transferable_list/move_up_highlighted"),
    TRANSFERABLE_LIST_SELECT("transferable_list/select"),
    TRANSFERABLE_LIST_SELECT_HIGHLIGHTED("transferable_list/select_highlighted"),
    TRANSFERABLE_LIST_UNSELECT("transferable_list/unselect"),
    TRANSFERABLE_LIST_UNSELECT_HIGHLIGHTED("transferable_list/unselect_highlighted"),

    // Widget
    WIDGET_BUTTON("widget/button"),
    WIDGET_BUTTON_DISABLED("widget/button_disabled"),
    WIDGET_BUTTON_HIGHLIGHTED("widget/button_highlighted"),
    WIDGET_CHECKBOX("widget/checkbox"),
    WIDGET_CHECKBOX_HIGHLIGHTED("widget/checkbox_highlighted"),
    WIDGET_CHECKBOX_SELECTED("widget/checkbox_selected"),
    WIDGET_CHECKBOX_SELECTED_HIGHLIGHTED("widget/checkbox_selected_highlighted"),
    WIDGET_CROSS_BUTTON("widget/cross_button"),
    WIDGET_CROSS_BUTTON_HIGHLIGHTED("widget/cross_button_highlighted"),
    WIDGET_LOCKED_BUTTON("widget/locked_button"),
    WIDGET_LOCKED_BUTTON_DISABLED("widget/locked_button_disabled"),
    WIDGET_LOCKED_BUTTON_HIGHLIGHTED("widget/locked_button_highlighted"),
    WIDGET_PAGE_BACKWARD("widget/page_backward"),
    WIDGET_PAGE_BACKWARD_HIGHLIGHTED("widget/page_backward_highlighted"),
    WIDGET_PAGE_FORWARD("widget/page_forward"),
    WIDGET_PAGE_FORWARD_HIGHLIGHTED("widget/page_forward_highlighted"),
    WIDGET_SCROLLER("widget/scroller"),
    WIDGET_SCROLLER_BACKGROUND("widget/scroller_background"),
    WIDGET_SLIDER("widget/slider"),
    WIDGET_SLIDER_HANDLE("widget/slider_handle"),
    WIDGET_SLIDER_HANDLE_HIGHLIGHTED("widget/slider_handle_highlighted"),
    WIDGET_SLIDER_HIGHLIGHTED("widget/slider_highlighted"),
    WIDGET_SLOT_FRAME("widget/slot_frame"),
    WIDGET_TAB("widget/tab"),
    WIDGET_TAB_HIGHLIGHTED("widget/tab_highlighted"),
    WIDGET_TAB_SELECTED("widget/tab_selected"),
    WIDGET_TAB_SELECTED_HIGHLIGHTED("widget/tab_selected_highlighted"),
    WIDGET_TEXT_FIELD("widget/text_field"),
    WIDGET_TEXT_FIELD_HIGHLIGHTED("widget/text_field_highlighted"),
    WIDGET_UNLOCKED_BUTTON("widget/unlocked_button"),
    WIDGET_UNLOCKED_BUTTON_DISABLED("widget/unlocked_button_disabled"),
    WIDGET_UNLOCKED_BUTTON_HIGHLIGHTED("widget/unlocked_button_highlighted"),

    // WorldList
    WORLD_LIST_ERROR("world_list/error"),
    WORLD_LIST_ERROR_HIGHLIGHTED("world_list/error_highlighted"),
    WORLD_LIST_JOIN("world_list/join"),
    WORLD_LIST_JOIN_HIGHLIGHTED("world_list/join_highlighted"),
    WORLD_LIST_MARKED_JOIN("world_list/marked_join"),
    WORLD_LIST_MARKED_JOIN_HIGHLIGHTED("world_list/marked_join_highlighted"),
    WORLD_LIST_WARNING("world_list/warning"),
    WORLD_LIST_WARNING_HIGHLIGHTED("world_list/warning_highlighted");

    private final String texture;

    GuiSprite(String texture) {
        this.texture = texture;
    }

    public String texture() {
        return texture;
    }

    public String atlas() {
        return "minecraft:gui";
    }
}
